aeternity/dex-ui

src/components/NotificationTransactionStatus.vue, src/lib/utils.js, src/store/modules/aeternity.js, src/store/plugins/pendingTransactionHandler.js
=> Fix transaction status notifiaction

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml
fixes #277 and supersedes #304
=> feat: adds issue templates

src/components/TokenSelector/SelectTokenModal.vue, src/components/TokenSelector/UserCustomTokensManager.vue, src/store/modules/tokens.js, src/views/RemoveLiquidity.vue
=> Fix remove liquidity

src/store/modules/aeternity.js
=> fix(add-liquidity-view): wrong ratios with dex-backend enabled

src/components/LiquidityDetails.vue, src/locales/en.json, src/locales/fr.json, src/views/ImportPool.vue
Fixes #392 
- for the import pool replace add & remove buttons with one button which sends the user back to the pool view
- change the 'Pool found message' with 'Your pool share was imported successfully'
=> feat(import-pool-view): ux changes

src/views/AddLiquidity.vue
=> fix(add-liquidity-view): restore tip message

package.json, src/components/ConfirmSwapModal.vue, src/lib/swapUtils.js, src/locales/en.json, src/locales/fr.json, src/mixins/setSwapRoutesMixin.js, src/views/SwapView.vue
=> feat(swap-view): high price impact warning

src/store/index.js
=> perf: try to connect with extenstion before enabling iframe wallet

src/components/ButtonToken.vue, src/components/ConfirmLiquidityModal.vue, src/components/ConfirmSwapModal.vue, src/components/LiquidityDetails.vue, src/components/LiquidityItem.vue, src/components/TokenAmountDetails.vue, src/components/TokenIcon.vue, src/components/TokenSelector/ListTokens.vue, src/components/TokenSelector/style.scss, src/lib/constants.js, src/store/modules/aeternity.js, src/views/RemoveLiquidity.vue
=> Show ae/wae image same everywhere

src/components/TokenSelector/SelectTokenModal.vue
=> fix(token-list): manage token list button on smaller displays

.env
=> feat(dex-backend): switch it on

src/components/Header.vue
=> feat: remove menu icons

src/components/Header.vue, src/locales/en.json, src/locales/fr.json, src/locales/zh-cn.json
=> feat: add Leave Feedback menu item

src/components/ConfirmLiquidityModal.vue, src/components/ErrorModal.vue, src/components/Header.vue, src/components/LiquidityDetails.vue, src/components/MainWrapper.vue, src/components/TokenSelector/TokenListManager.vue, src/locales/en.json, src/locales/fr.json, src/locales/zh-cn.json, src/views/AddLiquidity.vue, src/views/PoolView.vue, src/views/RemoveLiquidity.vue, src/views/SwapView.vue
last commit is based on [5ba8d19f720d2736c9c567dab41105b044a867fb](https://github.com/aeternity/dex-ui/pull/408/commits/5ba8d19f720d2736c9c567dab41105b044a867fb)
=> Refactoring

README.md
contribute.md link is missing because there is no file at the moment.
=> docs: adds readme

src/store/plugins/pendingTransactionHandler.js
=> fix(pending-transaction-handler): do not process unfinished transactions

src/store/modules/dexBackend.js
=> feat(dex-backend): restore token list fetching

src/components/SubmitTransactionModal.vue
=> refactor: skip confirmed submission modal on mobile

src/components/ConfirmSwapModal.vue, src/locales/en.json, src/locales/fr.json, src/locales/zh-cn.json, src/views/RemoveLiquidity.vue
fixes #446,
fixes #448,
fixes #449
=> fix: wording

src/locales/zh-cn.json
=> fix(translation): adjusts cn translation

src/components/TokenSelector/UserCustomTokensManager.vue
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/183240930-b1ccc105-0a16-4e69-a45b-b87195a79190.png)|![image](https://user-images.githubusercontent.com/9008074/183240986-9e2d1a91-5662-408e-9ab3-863bc5a3206b.png)|
=> fix(user-custom-tokens-manager): show token image correct size

src/router/index.js, src/views/AboutView.vue, src/views/NotFound.vue
=> feat: adds 404 fallback page

src/components/AboutModal.vue, src/components/Header.vue, src/components/InfoRow.vue, src/locales/en.json, src/locales/fr.json, src/locales/zh-cn.json, src/router/modals.js
=> feat: add the about dex modal

src/components/TermAndConditionModal.vue
=> feat(t&c): updates terms and conditions to v4

src/components/ButtonToken.vue, src/components/InputToken.vue, src/mixins/saveTokenSelectionMixin.js, src/views/SwapView.vue
=> Fix restoring selection

src/store/modules/aeternity.js
=> fix: amount with slippage for create_allowance on mobile

vue-svg-loader.js
=> fix(svg): make skip optimize flag works correctly

src/mixins/saveTokenSelectionMixin.js
=> fix: refresh page for non-default network and selected AE

src/views/SwapView.vue
=> fix(swap-view): insufficient funds button label

src/store/modules/tokens.js
=> fix: select token

src/lib/errors.js, src/lib/utils.js
=> feat: add extra info for low slippage errors
